### ISSUE TITLE
Dynamically link libunwind on musl

### ISSUE THREAD

**Issue by abenson** [benfred/remoteprocess#16]
Instead of forcing static link, could it be linked dynamically on systems that provide libunwind?

**Comment by benfred** [comment]
This shouldn't be too hard to do - its really just changing the check here https://github.com/benfred/remoteprocess/blob/ab5ae99c995812ffd8ecc52aaf548b10ba9cf8fa/build.rs#L17-L28  to link dynamically instead of statically.

The reason I'm only using static links for the musl target is that we're shipping [py-spy](https://github.com/benfred/py-spy) as a fully statically linked binary to make distribution easier to different platforms.

Which system are you thinking of?   Is there a way to detect that we should enable musl dynamic linking here - and still keep the benefits of static linking dpendencies on platforms like py-spy?

**Comment by abenson** [comment]
This is for the [Void Linux package](https://github.com/void-linux/void-packages/pull/22932).

Just being able to force it to build dynamically through a flag somehow would be fine.

**Comment by messense** [comment]
I also want this for alpine packaging: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/23220

**Comment by ericonr** [comment]
As a flag, an environment variable should just work.

**Comment by benfred** [comment]
Done with https://github.com/benfred/remoteprocess/pull/26
